### ISSUE TITLE
why can't recv msg in Android apk?

### ISSUE THREAD

**Issue by zbx911** [DeachSword/CHRLINE#15]
I used chrline added the Android versionfriends , I can see relevant information on chrline, but there is no infomation on Android, so is sending messages.

**Comment by WEDeach** [comment]
First you must provide more information:

1. did the friend have add you bot as a friend?
2. do you use sendMessage or with E2EE?
3. can you check that you bot did not get a talk ban?

**Comment by zbx911** [comment]
i used sendCompactMessage to send message,recv like this: [06:21:03] - from u85b4bf689261847d9913ae1fb103fc92 to {"mis": "u33667fda0fe9ad8eadab99a204e2e47f", "name": "zzzzz", "contactStatus": 1, "relationStatus": 0}, msg:test_friend_msg, reply:None.

**Comment by zbx911** [comment]
我通过chrline添加好友，显示是成功的，也能读取服务器好友信息，但是对方在安卓上看的时候，就没有我的信息。发送信息也一样，服务器提示发送成功，但是对方收不到。

**Comment by zbx911** [comment]
can i add your telegram?

**Comment by life91** [comment]
> First you must provide more information:
> 
> 1. did the friend have add you bot as a friend?
> 2. do you use sendMessage or with E2EE?
> 3. can you check that you bot did not get a talk ban?

when use sendMessage without e2ee, line server reply errorcode 82. how to solve it ? 

when use sendMessageWithE2EE, how to get selfKeyData? use API#requestSQR can get it ?

**Comment by WEDeach** [comment]
Hello, @life91 

> when use sendMessage without e2ee, line server reply errorcode 82. how to solve it ? 

you need to trun off your E2EE settings, try test_remove_e2ee_key.py in examples

> when use sendMessageWithE2EE, how to get selfKeyData? use API#requestSQR can get it ?

when you login via email or qrcode, it has a chance to help you get the e2ee key for let you use this feature

**Comment by WEDeach** [comment]
Hi, @zbx911 

Can u use sendMessage?
sendCompactMessage is for plain text messages without E2EE encryption, and currently it doesn't respond with any errors

**Comment by zbx911** [comment]
> Hi, @zbx911
> 
> Can u use sendMessage? sendCompactMessage is for plain text messages without E2EE encryption, and currently it doesn't respond with any errors

i remove all e2ee_key and reg new e2ee_key to deal this！
