### ISSUE TITLE
can you remove gevent,and add aiohttp？

### ISSUE THREAD

**Issue by zbx911** [DeachSword/CHRLINE#17]
upup

**Comment by WEDeach** [comment]
You should provide reasons.

Why should it be done and what has it changed?


Otherwise, you should clone and modify whatever you want.

**Comment by zbx911** [comment]
> 
1.Poor compatibility between gevent and pyinstaller.
2.An unknown error occurred in Gevent monkey patch.

**Comment by devkorn555** [comment]
Hey why  receiver_key_data[3] is -1   .....
![main py - Flush Line - Visual Studio Code  Administrator](https://user-images.githubusercontent.com/82007106/194526557-fdafbc92-88da-48ed-aa5a-b70ec29993c9.png)

**Comment by WEDeach** [comment]
not considering changing it at this stage
this may depend on some changes in pyinstaller to solve,
Btw: Gevent has some variables can be set, you can set them if you need

refs to https://github.com/pyinstaller/pyinstaller/issues/3648
