### ISSUE TITLE
Register feature error

### ISSUE THREAD

**Issue by Floweytale** [DeachSword/CHRLINE#3]
{'getPhoneVerifMethod': {'error': {'code': 1, 'message': 'A server error occurred.\nPlease try again.', 'metadata': {}}}}
Traceback (most recent call last):
  File "test_register.py", line 56, in <module>
    phone2 = cl.getPhoneVerifMethod(session, phone, region)[3] # 1 is availableMethods
KeyError: 3

**Comment by WEDeach** [comment]
can u see [SESSION] and [COUNTRY INFO]?

maybe is a limit of legy server, or the session is incorrect
