### ISSUE TITLE
Can you fix send Flex open chat?

### ISSUE THREAD

**Issue by vickysaputraa** [DeachSword/CHRLINE#31]
[sendLiff] issueLiffView error: Code: 3, Message: user consent required, Metadata: {3: {1: '1562242036', 2: 'https://access.line.me/oauth2/v2.1/authorize/consent?sessionString=ac5yaWgpbx5vKyVM0vaiYivSVFz1Q0MPgOWr0fBXpRTriC9k7gxQsDqQM4Qy89uM&client_id=1562242036&scope=profile+chat_message.write&redirect_uri=https%3A%2F%2Fline-app.tenor.com%2F&response_type=code&prompt=consent&type=LL&lang=en_EN'}}

**Comment by WEDeach** [comment]
OpenChat is always under development, it will not be the highest priority

**Comment by WEDeach** [comment]
Hello, 

After testing, this is very easy to fix 👍 
It will use `https://access.line.me/oauth2/v2.1/authorize/consent` for user consent

I expect it will be added in v2.0.0-b13.
plz understand, OpenChat has always been a project I work on, 
but I'm still learning how they use the `/PUSH` endpoint

**Comment by vickysaputraa** [comment]
> 

thankss 🥰🥰

**Comment by WEDeach** [comment]
Fixed on   48fd9c5b167cde7ef20c50d54247f4b5ff5d4093
