### ISSUE TITLE
findAndAddContactsByPhone and findContactsByPhone?

### ISSUE THREAD

**Issue by Jaamjun** [DeachSword/CHRLINE#41]
I want to use the function findAndAddContactsByPhone and findContactsByPhone, The old documents have never been used by anyone. Can you give me some advice?

**Comment by WEDeach** [comment]
Hello, @Jaamjun 

Have you tried using those functions?
* **yes**:  provide the exceptions or log, etc.
* **no**:  check what exceptions you will get

**Comment by WEDeach** [comment]
reply if have any updates
