### ISSUE TITLE
E2EE Message is not working for iOS users

### ISSUE THREAD

**Issue by OwXi** [DeachSword/CHRLINE#5]
For some reasons, E2EE message is not working on iOS (but works perfectly fine on mac, windows and android).
[Code](https://github.com/DeachSword/CHRLINE/blob/master/examples/test_e2ee_send_message.py)

![image](https://user-images.githubusercontent.com/77071438/131264917-1160fd40-6266-4cd5-9417-0cd0d1a5e6df.png)
[Image from GKZ on repo's discord](https://ptb.discord.com/channels/466066749440393216/879796531870445601/881637212112969768)

**Comment by vickysaputraa** [comment]
func def cl.sendMessageWithChunks errors relatedMessageId is None?

CHRLINE.exceptions.LineServiceException: Code: 0, Message: invalid message: relatedMessageId

**Comment by WEDeach** [comment]
> func def cl.sendMessageWithChunks errors relatedMessageId is None?
> 
> CHRLINE.exceptions.LineServiceException: Code: 0, Message: invalid message: relatedMessageId

Avoid make relatedMessageId as None, this problem will be resolved in the next version

**Comment by vickysaputraa** [comment]
> 



> > func def cl.sendMessageWithChunks errors relatedMessageId is None?
> > CHRLINE.exceptions.LineServiceException: Code: 0, Message: invalid message: relatedMessageId
> 
> Avoid make relatedMessageId as None, this problem will be resolved in the next version

so relatedMessageId = None changed what?

**Comment by WEDeach** [comment]
I can't check if it works, v2.0 should get fixed

**Comment by WEDeach** [comment]
refs to https://github.com/DeachSword/CHRLINE/commit/3dda93b9b41eadb7a9a226db16a390f1d46ef31d
