### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Anwenya** [DeachSword/CHRLINE#55]
when i run like this
```
CHRLINE(authTokenOrEmail="", password="")
```
Then remind me to type in pincode, 

When I type in pincode on my phone,the line app reminds me

**Unable to process, please try again later**

Tried many times, but it didn't work

The odd thing is that every time it reminds me that I need to enter the same pincode

Usually pincode is different every time, i think.

I use the proxy ip address, will it affect?

**Comment by WEDeach** [comment]
*PLEASE* provide any valid information, such as chrline version, python version, and error log...
remember that, you are not opening an issue because you have a problem, but so that a developer can reproduce the problems.
