### ISSUE TITLE
Thrift协议

### ISSUE THREAD

**Issue by zwllh123** [DeachSword/CHRLINE#58]
可以详细说明下thrift协议构造吗，想做一个C#版本的机器人开源

**Comment by WEDeach** [comment]
Thrift不是本專案負責的範圍唷
請參考
https://thrift.apache.org/

任何有關於Thrift的疑問都不應該在此提問。

**Comment by zwllh123** [comment]
你好，是想咨询下line的通信协议，就是您python里边各个数组传值的这个问题
