### ISSUE TITLE
This service isn't available in your region or app version.

### ISSUE THREAD

**Issue by angeloqianyon** [DeachSword/CHRLINE#59]
{'error': {'code': 403, 'message': "This service isn't available in your region or app version.", 'metadata': None, '_data': {1: 403, 3: "This service isn't available in your region or app version."}}}
[2023-04-27 19:54:57] Not support Square: This service isn't available in your region or app version.

When I use login_web, I encounter the error mentioned above. Has anyone experienced this issue? The number is from Thailand.

**Comment by WEDeach** [comment]
It's not CHRLINE problem, please make sure you use the service correctly
