### ISSUE TITLE
HumanVerif function isn't exist.

### ISSUE THREAD

**Issue by open-ki** [DeachSword/CHRLINE#6]
in examples/test_register.py
```python
hv = HumanVerif(verify['error']['metadata'][11][1], verify['error']['metadata'][11][2])
RetryReq(session, hv)
```
and `verify['error']['metadata']` does not return anything

**Comment by WEDeach** [comment]
Hello @open-ki ,

func_HumanVerif is a custom function, so yes itnt exist.

For the metadata is empty, need more detailed, can u print the errors?

**Comment by open-ki** [comment]
solved by changing APP_NAME to `ANDROID\t9.12.0\tAndroid OS\t10` and USER_AGENT to `9.12.0`
to avoid reCaptcha

**Comment by cyztalzboyz** [comment]
> solved by changing APP_NAME to `ANDROID\t9.12.0\tAndroid OS\t10` and USER_AGENT to `9.12.0`
> to avoid reCaptcha

Sorry, Now i register with indo number. I have same error too. Please help.

**Comment by IllusionZG** [comment]
Now you'll have to solve captcha, with 3rd party or with selenium to open captcha then solve it by yourself

**Comment by gokusenz** [comment]
> Now you'll have to solve captcha, with 3rd party or with selenium to open captcha then solve it by yourself

Is it possible to share the code with selenium to open a captcha?

I've tried to use selenium but it doesn't work T.T

**Comment by IllusionZG** [comment]
> > Now you'll have to solve captcha, with 3rd party or with selenium to open captcha then solve it by yourself
> 
> Is it possible to share the code with selenium to open a captcha?
> 
> I've tried to use selenium but it doesn't work T.T

@gokusenz Join the discord server of this repo's README
