### ISSUE TITLE
选择CHN注册的时候提示,伺服服务器错误

### ISSUE THREAD

**Issue by zwllh123** [DeachSword/CHRLINE#60]
![image](https://user-images.githubusercontent.com/4363115/235311261-6980890b-3f75-40ed-b388-687201a0cf0d.png)
"C:\Python311\Lib\site-packages\CHRLINE\models.py", line 650, in postPackDataAndGetUnpackRespData
    raise LineServiceException(res["error"])
CHRLINE.exceptions.LineServiceException: Code: 1, Message: 伺服器發生錯誤

**Comment by zwllh123** [comment]
![image](https://user-images.githubusercontent.com/4363115/235311607-d148efde-4146-49bd-891a-53be20cefc9d.png)
使用CH后一直提示电话号码无效

**Comment by zwllh123** [comment]
![image](https://user-images.githubusercontent.com/4363115/235311822-0b1cf46f-656b-4b16-ab0f-5d1a82852a58.png)
cn也是电话号码不正确

**Comment by WEDeach** [comment]
https://baike.baidu.com/item/ISO%203166-1?fromModule=lemma_search-box

了解一下, 要二位不是3位, 要大寫不是小寫
再有錯誤就是LINE不支持中國號碼.
