### ISSUE TITLE
Signup primary does not send pin

### ISSUE THREAD

**Issue by Syedabbasrazashah** [DeachSword/CHRLINE#65]
requestToSendPhonePinCode does not send pin soemhow, may be anything changed? @

**Comment by WEDeach** [comment]
Hi @Syedabbasrazashah 
**PLEASE** provide a runnable script for testing or any information available to reproduce the problem :D

**Comment by WEDeach** [comment]
Please give me more useful information, such as the beginning of the phone number and the country
If you can see other func responses (besides session), please also provide.

**Comment by WEDeach** [comment]
After testing, the script still works.

Have a nice day!

**Comment by KYSStudio** [comment]
Sure. I'm using Netherlands with Netherlands's IP. (+31 for phone code).
I have also tried with HK(+852), and MY(+60).
If you would like to, I can provide you the related information such as phone number.

Specify to describe, the test_register.py will tell you it sends the PIN, but we will get nothing on the number.

**Comment by WEDeach** [comment]
Hello @KYSStudio,

I will test the script for you to check if it is still working, as a courtesy to you :D

**Comment by WEDeach** [comment]
After testing, the script still works
I did receive the PinCode.

now, close again 🙂

**Comment by KYSStudio** [comment]
Okay. No worries.
I just tested with my two Hong Kong phone numbers (real numbers) and get nothing.
However, when I request a normal register operation via LINE App, it did send the code.
Would you like to test the script with region other than TW? Appreciate it! I can provide real HK number (which is mine).

**Comment by WEDeach** [comment]
Hi @KYSStudio,

Sry, I only checked whether the script works, it will be different for different uses, that is something you need to know first.

If this script works for the minority, then I can't help, why? Because I can't reproduce the problem. And most of the reason comes from LINE limitations rather than this library.

> However, when I request a normal register operation via LINE App, it did send the code.

then I highly recommend you to join Discord and upload video for your registration process 👍
