### ISSUE TITLE
E2EE: input must be 32-byte string

### ISSUE THREAD

**Issue by nn29nap** [DeachSword/CHRLINE#68]
Is E2EE outdated? I have try to decrypt E2EE message with decryptE2EETextMessage method it not working

```
    def recvMessage(self, op, cl):
        msg = op.message
        if msg.isE2EE:
            print(cl.decryptE2EETextMessage(msg))
        else:
            print(msg)
```

```
File "/Users/nn29nap/Desktop/CHRLINE/CHRLINE/e2ee.py", line 97, in generateSharedSecret
    curve25519 = Curve25519.calculateAgreement(bytes(private_key), bytes(public_key))
ValueError: input must be 32-byte string
```

**Comment by WEDeach** [comment]
Hi @nn29nap,

Just check your private_key and public_key :)

**Comment by nn29nap** [comment]
Thank your for your quick response @WEDeach, I checked in CHRLINE package directory. There are .e2eeGroupKeys .e2eeKeys and e2eePublicKeys existing with json files.

**Comment by WEDeach** [comment]
Hi @nn29nap,

So... have you checked that the key is correct?
decode base64 and check that the length is 32-byte.

----
Furthermore, I don't recommend that you view it from files, try use model function to call it, 
for example:
https://github.com/DeachSword/CHRLINE/blob/b08a9f2c186c0e7d4ee2e2bfc6f83e2c8915a9b5/CHRLINE/e2ee.py#L184

and deocde with base64:
https://github.com/DeachSword/CHRLINE/blob/b08a9f2c186c0e7d4ee2e2bfc6f83e2c8915a9b5/CHRLINE/e2ee.py#L189

----
If the private key is correct, then you may want to check if the recipient's public key is legitimate:
https://github.com/DeachSword/CHRLINE/blob/b08a9f2c186c0e7d4ee2e2bfc6f83e2c8915a9b5/CHRLINE/e2ee.py#L190-L197

----
You can even debug them manually:
https://github.com/DeachSword/CHRLINE/blob/b08a9f2c186c0e7d4ee2e2bfc6f83e2c8915a9b5/examples/test_e2ee_send_message.py#L7-L25

**Comment by nn29nap** [comment]
https://github.com/DeachSword/CHRLINE/blob/b08a9f2c186c0e7d4ee2e2bfc6f83e2c8915a9b5/CHRLINE/e2ee.py#L304-L307

For decrypt private message result:
`
ValueError: Padding is incorrect.`


https://github.com/DeachSword/CHRLINE/blob/b08a9f2c186c0e7d4ee2e2bfc6f83e2c8915a9b5/CHRLINE/e2ee.py#L309
For decrypt group message result:
`
ValueError: input must be 32-byte string`

I'm not sure that result printed of private key doesn't look like base64 string so after decoded **privKey** may it caused into invalid  32-byte?

`{'privKey': 'mC6p2EQzfsLU4vco6r7MXHMGho+afz9TQHtsJVTDY7M/rzG8dq1i2TwKL2vffAZI', 'keyId': 80920632}`

**Comment by WEDeach** [comment]
Hello @nn29nap,

Becareful, no matter what the error is, I only care about whether the key is legal.
But why? because most of the errors come from wrong keys 🙂

----
> I'm not sure that result printed of private key doesn't look like base64 string so after decoded privKey may it caused into invalid 32-byte?

So you just "look" it? Instead of trying to decode it?
